FE - Bottom NavBar completed
serhii-fsi/good-neighbour pull request #107
Opened 2024-05-28 14:38 UTC by shaquillekiragu

2024-05-28 14:53 UTC, Mpanasetckiy requested changes

2024-05-29 08:38 UTC, Mpanasetckiy requested changes

2024-05-29 08:38 UTC, Mpanasetckiy commented on frontend_/src/components/NavBottom/NavBottom.jsx
> +    const { routes } = config;
routes to the view pls

2024-05-29 08:38 UTC, Mpanasetckiy commented on frontend_/src/components/NavBottom/NavBottomView.jsx
> +                    <SearchOutlined style={{ width: "50px" }} />
styling, no px pls for menu icons, sizes hve to be responsive

2024-05-29 16:18 UTC, serhii-fsi approved these changes

2024-05-29 16:18 UTC, Mpanasetckiy approved these changes
Well done

2024-05-29 16:18 UTC, merged